[package]
name = "svh-bot"
version = "0.1.0"
authors = ["Alex Krantz <alex@krantz.dev>"]
edition = "2018"

[dependencies]
dotenv = "^0.15.0"
leg = "^0.4"

[dependencies.serenity]
features = ["framework", "standard_framework", "rustls_backend"]
version = "^0.8"
