[package]
name = "svh-bot"
version = "0.1.0"
authors = ["Alex Krantz <alex@krantz.dev>"]
edition = "2018"

[dependencies]
chrono = "^0.4"
dotenv = "^0.15.0"
env_logger = "^0.7"
lazy_static = "^1.4"
log = "^0.4"
rand = "^0.7"
redis = "^0.15"
serenity = "^0.8"
